version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    env_file: .env
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.2
    env_file: .env
    ports:
      - '${MOODLE_PORT1}:8080'
      - '${MOODLE_PORT2}:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local